---

    # Centos7 requires the scl package to enable fetching packages from software collections
    - name: Install software collections (Centos)
        yum: 
            name:
                - centos-release-scl
            state: latest
            use_backend: yum
        become: yes

    - name: Add EPEL repository from artifactory (Centos 7)
        yum_repository:
            name: epel
            description: EPEL YUM repo
            baseurl: https://artifactory.ccdc.cam.ac.uk/public-epel-7-mirror/
            gpgkey: https://artifactory.ccdc.cam.ac.uk/ccdc-3rd-party-sources/RPM-GPG-KEY-EPEL-7
        become: yes
    when: ansible_distribution_major_version == '7'"

    # Centos7 provides an extremely old mercurial 
    - name: Add mercurial repository (Centos7)
        yum_repository:
            name: mercurial.selenic.com
            description: mercurial YUM repo
            baseurl: https://www.mercurial-scm.org/release/centos7
            gpgcheck: no
        become: yes
    when: ansible_distribution_major_version == '7'"
