---
  # Modern clang on centos7? Why not!
  - name: Add llvm-toolset-10 repository from cloudlinux
    yum_repository:
      name: cloudlinux-llvm-toolset-10.0
      description: llvm-toolset-10 repository from cloudlinux
      # mirror of https://repo.cloudlinux.com/cloudlinux/7/sclo/llvm-toolset-10.0
      baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-cloudlinux-llvm-toolset-10.0/
      gpgcheck: no
      username: "{{ansible_deployment_artifactory_user}}"
      password: "{{ansible_deployment_artifactory_key}}"
    become: yes

  - name: Add oracle linux 7's ol7_software_collections repository
    yum_repository:
      name: ol7_software_collections
      description: ol7_software_collections
      # mirror of http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/
      baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-ol7-scl/
      gpgcheck: no
      username: "{{ansible_deployment_artifactory_user}}"
      password: "{{ansible_deployment_artifactory_key}}"
    become: yes

  - name: Add EPEL repository from artifactory
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-epel-7-mirror/
      gpgkey: https://artifactory.ccdc.cam.ac.uk/artifactory/ccdc-3rd-party-sources/RPM-GPG-KEY-EPEL-7
      username: "{{ansible_deployment_artifactory_user}}"
      password: "{{ansible_deployment_artifactory_key}}"
    become: yes

  # Centos7 provides an extremely old mercurial 
  - name: Add Mercurial repository
    yum_repository:
      name: mercurial.selenic.com
      description: mercurial YUM repo
      baseurl: https://www.mercurial-scm.org/release/centos7/
      # Artifactory mirror is not working with an https range error
      # baseurl: https://artifactory.ccdc.cam.ac.uk/artifactory/public-mercurial-centos-7-mirror/
      gpgcheck: no
    become: yes

  # Centos7 requires the scl package to enable fetching packages from software collections
  - name: Install software collections
    package:
      name:
        - centos-release-scl
      state: latest
    become: yes
