---
- name: Check the Command Line Tools package metadata
  ansible.builtin.command: pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
  register: clt_pkg_info
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: "Download command line tools dmg"
  ansible.builtin.get_url:
    url: https://artifactory.ccdc.cam.ac.uk/artifactory/ccdc-3rdparty-macos-xcode-installers/Command_Line_Tools_for_Xcode_12.4.dmg
    dest: "{{ ansible_env.HOME }}/Downloads/Command_Line_Tools_for_Xcode_12.4.dmg"
    mode: 0755
    url_username: "{{ ansible_deployment_artifactory_user }}"
    headers:
      X-JFrog-Art-Api: "{{ ansible_deployment_artifactory_key }}"
  when: clt_pkg_info.rc != 0

- name: Create temporary download directory for command line tools
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Downloads/clt"
    state: directory
    mode: '0755'
  when: clt_pkg_info.rc != 0

- name: "Mount command line tools dmg"  # noqa: no-changed-when
  ansible.builtin.command: hdiutil attach "{{ ansible_env.HOME }}/Downloads/Command_Line_Tools_for_Xcode_12.4.dmg" -nobrowse -mountpoint "{{ ansible_env.HOME }}/Downloads/clt"
  when: clt_pkg_info.rc != 0

- name: Install command line tools package  # noqa: no-changed-when
  ansible.builtin.command: installer -pkg "{{ ansible_env.HOME }}/Downloads/clt/Command Line Tools.pkg" -target /
  when: clt_pkg_info.rc != 0
  become: true

- name: Check the Command Line Tools package metadata (after install)  # noqa: no-changed-when
  ansible.builtin.command: pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
  when: clt_pkg_info.rc != 0

- name: "Unmount command line tools dmg"  # noqa: no-changed-when
  ansible.builtin.command: hdiutil detach "{{ ansible_env.HOME }}/Downloads/clt"
  when: clt_pkg_info.rc != 0

- name: "Remove command line tools dmg mountpoint"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Downloads/clt"
    state: absent

- name: Install homebrew
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
