---
# We have no artifactory EPEL mirror for Rocky so we'll just install the distribution's own
- name: Import EPEL GPG key.
  ansible.builtin.rpm_key:
    key: "{{ epel_key}}"
    state: present
  become: true

- name: Install EPEL
  ansible.builtin.dnf:
    name: "{{ epel_file }}"
    enable_plugin: crb
    state: present
  become: true
