---
# We have no artifactory EPEL mirror for Rocky so we'll just install the distribution's own
- name: Install EPEL
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    enable_plugin: crb
    state: present
