---
# We have no artifactory EPEL mirror for Rocky so we'll just install the distribution's own
- name: Import EPEL GPG key.
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  become: true

- name: Install EPEL
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    enable_plugin: crb
    state: present
  become: true
