---
- name: Check if Chocolatey is already installed
  ansible.windows.win_shell: "& (Get-Command choco).Path -v"
  ignore_errors: true
  register: choco

- name: Set result as fact with default 0
  ansible.builtin.set_fact:
    choco_version: "{{ choco.stdout | default('0.1.0', true) }}"

- name: Ensure prerequisites for Chocolatey are installed
  when: choco_version is version('2.0.0', '<')
  block:
    - name: Install Chocolatey CLI v1.4.0
      chocolatey.chocolatey.win_chocolatey:
        name: "chocolatey"
        state: present
        version: "1.4.0"
        force: true
      become: true

    - name: Install Microsoft .NET Framework 4.8
      chocolatey.chocolatey.win_chocolatey:
        name: "netfx-4.8"
        state: present
      become: true

    - name: Reboot the host to complete .NET Framework 4.8 install
      ansible.windows.win_reboot:
        post_reboot_delay: 180
      become: true

- name: Install Chocolatey CLI v2.0.0+ when .NET Framework 4.8 dependency is met
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: latest
  become: true

- name: Remove default Chocolatey source and old CCDC sources
  chocolatey.chocolatey.win_chocolatey_source:
    name: "{{ source }}"
    state: absent
  loop:
    - "chocolatey"
    - "ccdc chocolatey mirror"
    - "internal repo"
  loop_control:
    loop_var: source
  become: true

- name: Add sources to choco
  chocolatey.chocolatey.win_chocolatey_source:
    name: "{{ chocolatey_source_name }}"
    state: present
    source: "{{ item }}"
    source_username: "{{ chocolatey_mirror_username }}"
    source_password: "{{ chocolatey_mirror_password }}"
  become: true
  loop: "{{ chocolatey_source_url }}"